"use client";

import { useState, useRef, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { AlertCircle, CheckCircle2, Mail, Upload, Store } from 'lucide-react';
import Link from 'next/link';
import Image from 'next/image';

export default function RegisterPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [name, setName] = useState('');
  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(false);
  const [brandName, setBrandName] = useState('');
  const [brandLogo, setBrandLogo] = useState<string | null>(null);
  const [headerImage, setHeaderImage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [registeredEmail, setRegisteredEmail] = useState<string | null>(null);
  const [showVerificationMessage, setShowVerificationMessage] = useState(false);
  
  const logoInputRef = useRef<HTMLInputElement>(null);
  const headerInputRef = useRef<HTMLInputElement>(null);
  const router = useRouter();
  const searchParams = useSearchParams();

  // Load email from URL parameter on component mount
  useEffect(() => {
    const emailParam = searchParams.get('email');
    if (emailParam) {
      setEmail(emailParam);
      
      // Auto-generate name from email
      const username = emailParam.split('@')[0] || '';
      const formattedName = username
        .split(/[._-]/)
        .map(part => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
      setName(formattedName);
      setIsNameAutoGenerated(true);
    }
  }, [searchParams]);

  // Handle email change
  const handleEmailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newEmail = e.target.value;
    setEmail(newEmail);
    
    if (!name || isNameAutoGenerated) {
      const username = newEmail.split('@')[0] || '';
      const formattedName = username
        .split(/[._-]/)
        .map(part => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
      setName(formattedName);
      setIsNameAutoGenerated(true);
    }
  };

  // Handle name focus
  const handleNameFocus = () => {
    if (isNameAutoGenerated) {
      setName('');
      setIsNameAutoGenerated(false);
    }
  };

  // Handle name blur
  const handleNameBlur = () => {
    if (!name.trim()) {
      const username = email.split('@')[0] || '';
      const formattedName = username
        .split(/[._-]/)
        .map(part => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
      setName(formattedName);
      setIsNameAutoGenerated(true);
    }
  };

  // Handle logo change
  const handleLogoChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setBrandLogo(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  // Handle header change
  const handleHeaderChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setHeaderImage(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  // Handle form submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError(null);

    try {
      const formData = new FormData();
      formData.append('email', email);
      formData.append('password', password);
      formData.append('name', name);
      formData.append('brandName', brandName);
      
      if (brandLogo) {
        const logoFile = logoInputRef.current?.files?.[0];
        if (logoFile) formData.append('logoFile', logoFile);
      }
      
      if (headerImage) {
        const headerFile = headerInputRef.current?.files?.[0];
        if (headerFile) formData.append('headerFile', headerFile);
      }

      const response = await fetch('/api/auth/register', {
        method: 'POST',
        body: formData,
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Registration failed');
      }

      setRegisteredEmail(email);
      setShowVerificationMessage(true);
    } catch (error) {
      console.error('Registration error:', error);
      setError(error instanceof Error ? error.message : 'Registration failed. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Handle resend verification email
  const handleResendVerification = async () => {
    if (!registeredEmail) return;
    
    // Clear any previous messages
    setError(null);
    setSuccess(null);
    setIsSubmitting(true);
    
    try {
      const response = await fetch('/api/auth/resend-verification', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ email: registeredEmail }),
      });
      
      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Failed to resend verification email');
      }
      
      setSuccess('Verification email has been resent');
      
      // Clear success message after 5 seconds
      setTimeout(() => {
        setSuccess(null);
      }, 5000);
    } catch (error) {
      console.error('Resend verification error:', error);
      setError(error instanceof Error ? error.message : 'Failed to resend verification email');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-stone-50 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full mx-auto">
        <div className="flex flex-col items-center mb-8">
          <Link href="/" className="mb-4">
            <Image 
              src="/logo.png" 
              alt="Alacart Logo" 
              width={100} 
              height={21} 
              className="h-auto"
              priority
            />
          </Link>
          {!showVerificationMessage &&         
            <CardHeader className="text-center">
              <CardTitle className="text-3xl font-light mb-1">Get Started</CardTitle>
              <CardDescription className="text-xl text-stone-500 font-light">Create your account to continue</CardDescription>
            </CardHeader>
          }
        </div>
        
        <Card className="w-full max-w-md py-8">
          <h3 className="text-xl font-light text-center">Account Information</h3>
          <p className="text-stone-500 font-light mb-4 text-center">Tell us about yourself</p>
          <CardContent>
            {error && (
              <Alert variant="destructive" className="mb-4 rounded-xl">
                <AlertCircle className="h-4 w-4" />
                <AlertTitle>Error</AlertTitle>
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            )}
            
            {!showVerificationMessage ? (
              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="space-y-4 border-b border-stone-200 pb-12 mb-8">
                  <div>
                    <Label htmlFor="email" className="text-stone-700 font-light">Email</Label>
                    <Input
                      id="email"
                      type="email"
                      value={email}
                      onChange={handleEmailChange}
                      placeholder="you@example.com"
                      className="border-stone-300 rounded-2xl h-12 font-light focus:border-emerald-500 focus:ring-emerald-500"
                      required
                    />
                  </div>
                  
                  <div>
                    <Label htmlFor="password" className="text-stone-700 font-light">Password</Label>
                    <Input
                      id="password"
                      type="password"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      placeholder="••••••••"
                      className="border-stone-300 rounded-2xl h-12 font-light focus:border-emerald-500 focus:ring-emerald-500"
                      required
                      minLength={8}
                    />
                    <p className="text-xs text-stone-500 font-light mt-1">
                      Password must be at least 8 characters with uppercase, lowercase, numbers, and special characters
                    </p>
                  </div>
                  
                  <div>
                    <Label htmlFor="name" className="text-stone-700 font-light">Full Name (Optional)</Label>
                    <Input
                      id="name"
                      type="text"
                      value={name}
                      onChange={(e) => {
                        setName(e.target.value);
                        setIsNameAutoGenerated(false);
                      }}
                      onFocus={handleNameFocus}
                      onBlur={handleNameBlur}
                      placeholder={isNameAutoGenerated ? name : 'Your name'}
                      className="border-stone-300 rounded-2xl h-12 font-light focus:border-emerald-500 focus:ring-emerald-500"
                    />
                  </div>
                </div>
                {/* Brand Information */}
                <div>
                  <h3 className="text-xl font-light text-center">Brand Settings</h3>
                  <p className="text-stone-500 font-light mb-4 text-center">Customize your brand's appearance (optional)</p>
                  
                  <div className="space-y-4">
                    <div className="my-6">
                      <Label htmlFor="brand-name" className="text-stone-700 font-light mb-2 block">Brand Name</Label>
                      <Input 
                        id="brand-name" 
                        type="text" 
                        value={brandName} 
                        onChange={(e) => setBrandName(e.target.value)} 
                        placeholder="Your Brand Name"
                        className="border-stone-300 rounded-2xl h-12 font-light focus:border-emerald-500 focus:ring-emerald-500"
                      />
                    </div>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div>
                        <Label className="text-stone-700 font-light mb-2 block">Brand Logo</Label>
                        <div className="border border-dashed border-stone-300 rounded-2xl p-4 flex flex-col items-center justify-center cursor-pointer hover:bg-stone-50 transition-colors"
                             onClick={() => logoInputRef.current?.click()}>
                          <div className="relative w-28 h-28 mb-2 group">
                            {brandLogo ? (
                              <>
                                <Image 
                                  src={brandLogo} 
                                  alt="Brand logo" 
                                  fill 
                                  className="object-cover rounded-xl group-hover:opacity-80 transition-opacity" 
                                  unoptimized={brandLogo.startsWith('data:')} 
                                />
                                <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                                  <div className="bg-black bg-opacity-50 text-white text-xs rounded-lg px-2 py-1">
                                    Change Logo
                                  </div>
                                </div>
                              </>
                            ) : (
                              <div className="w-full h-full bg-stone-100 rounded-xl flex flex-col items-center justify-center group-hover:bg-stone-200 transition-colors">
                                <Store className="h-10 w-10 text-stone-400 mb-2 group-hover:scale-110 transition-transform" />
                                <span className="text-xs text-stone-500">Upload Logo</span>
                              </div>
                            )}
                          </div>
                          <input
                            type="file"
                            ref={logoInputRef}
                            onChange={handleLogoChange}
                            accept="image/jpeg,image/png,image/webp"
                            className="hidden"
                          />
                          <p className="text-xs text-stone-500 mt-2">JPG, PNG, WebP</p>
                          <p className="text-xs text-stone-500">(max 2MB)</p>
                        </div>
                      </div>
                      
                      <div>
                        <Label className="text-stone-700 font-light mb-2 block">Header Image</Label>
                        <div className="border border-dashed border-stone-300 rounded-2xl p-4 flex flex-col items-center justify-center cursor-pointer hover:bg-stone-50 transition-colors"
                             onClick={() => headerInputRef.current?.click()}>
                          <div className="relative w-full h-28 mb-2 group">
                            {headerImage ? (
                              <>
                                <Image 
                                  src={headerImage} 
                                  alt="Header image" 
                                  fill 
                                  className="object-cover rounded-xl group-hover:opacity-80 transition-opacity" 
                                  unoptimized={headerImage.startsWith('data:')} 
                                />
                                <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                                  <div className="bg-black bg-opacity-50 text-white text-xs rounded-lg px-2 py-1">
                                    Change Header
                                  </div>
                                </div>
                              </>
                            ) : (
                              <div className="w-full h-full bg-stone-100 rounded-xl flex flex-col items-center justify-center group-hover:bg-stone-200 transition-colors">
                                <Upload className="h-10 w-10 text-stone-400 mb-2 group-hover:scale-110 transition-transform" />
                                <span className="text-xs text-stone-500">Upload Header</span>
                              </div>
                            )}
                          </div>
                          <input
                            type="file"
                            ref={headerInputRef}
                            onChange={handleHeaderChange}
                            accept="image/jpeg,image/png,image/webp"
                            className="hidden"
                          />
                          <p className="text-xs text-stone-500 mt-2">JPG, PNG, WebP</p>
                          <p className="text-xs text-stone-500">(max 2MB)</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                
                <Button 
                  type="submit" 
                  className="w-full bg-emerald-600 hover:bg-emerald-700 text-white rounded-2xl h-12 font-light" 
                  disabled={isSubmitting}
                >
                  {isSubmitting ? 'Creating Account...' : 'Create Account'}
                </Button>
              </form>
            ) : (
              <div className="text-center py-8">
                <div className="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <Mail className="h-8 w-8 text-emerald-600" />
                </div>
                <h3 className="text-xl font-light text-stone-800 mb-2">Check your email</h3>
                <p className="text-stone-600 mb-6">We've sent a verification link to <span className="font-medium">{registeredEmail}</span></p>
                
                {success && (
                  <Alert className="mb-4 bg-emerald-50 border-emerald-200">
                    <CheckCircle2 className="h-4 w-4 text-emerald-600" />
                    <AlertTitle className="text-emerald-600 font-normal">Success</AlertTitle>
                    <AlertDescription className="text-emerald-700 font-light">
                      {success}
                    </AlertDescription>
                  </Alert>
                )}
                
                {error && (
                  <Alert className="mb-4 bg-red-50 border-red-200">
                    <AlertCircle className="h-4 w-4 text-red-600" />
                    <AlertTitle className="text-red-600 font-normal">Error</AlertTitle>
                    <AlertDescription className="text-red-700 font-light">
                      {error}
                    </AlertDescription>
                  </Alert>
                )}
                
                <Button 
                  variant="outline" 
                  onClick={handleResendVerification}
                  className="text-emerald-600 border-emerald-200 hover:bg-emerald-50"
                  disabled={isSubmitting}
                >
                  Resend verification email
                </Button>
              </div>
            )}
            
            <div className="mt-4 text-center text-sm text-stone-600 font-light">
              Already have an account?{' '}
              <Link href="/login" className="text-emerald-600 hover:text-emerald-700 font-light">
                Sign in
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
