"use client";

import { useState, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { AlertCircle, CheckCircle2, Mail, Upload, Store } from 'lucide-react';
import Link from 'next/link';
import Image from 'next/image';

export default function RegisterPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [name, setName] = useState('');
  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(false);
  
  // Store branding state
  const [storeName, setStoreName] = useState('');
  const [storeDescription, setStoreDescription] = useState('');
  const [storeLogo, setStoreLogo] = useState<string | null>(null);
  const [headerImage, setHeaderImage] = useState<string | null>(null);
  
  // Form state
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [registeredEmail, setRegisteredEmail] = useState<string | null>(null);
  const [showVerificationMessage, setShowVerificationMessage] = useState(false);
  
  // Refs for file inputs
  const logoInputRef = useRef<HTMLInputElement>(null);
  const headerInputRef = useRef<HTMLInputElement>(null);
  
  const router = useRouter();
  
  // Generate name from email when email changes
  const handleEmailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newEmail = e.target.value;
    setEmail(newEmail);
    
    // Only auto-fill name if it's empty or was auto-generated
    if (!name || isNameAutoGenerated) {
      const username = newEmail.split('@')[0] || '';
      const formattedName = username
        .split(/[._-]/)
        .map(part => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
      setName(formattedName);
      setIsNameAutoGenerated(true);
    }
  };
  
  // Clear auto-generated name when user focuses on name field
  const handleNameFocus = () => {
    if (isNameAutoGenerated) {
      setName('');
      setIsNameAutoGenerated(false);
    }
  };

  // Restore auto-generated name when name field loses focus and is empty
  const handleNameBlur = () => {
    if (!name.trim() && email) {
      const username = email.split('@')[0] || '';
      const formattedName = username
        .split(/[._-]/)
        .map(part => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
      setName(formattedName);
      setIsNameAutoGenerated(true);
    }
  };
  // Handle logo file selection
  const handleLogoChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    
    // Validate file type
    if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) {
      setError("Logo must be JPG, PNG, or WebP format");
      return;
    }
    
    // Validate file size (max 2MB)
    if (file.size > 2 * 1024 * 1024) {
      setError("Logo must be less than 2MB");
      return;
    }
    
    // Clear any previous errors
    setError(null);
    
    // Create a preview URL
    const reader = new FileReader();
    reader.onload = (event) => {
      setStoreLogo(event.target?.result as string);
    };
    reader.readAsDataURL(file);
  };
  
  // Handle header image file selection
  const handleHeaderChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    
    // Validate file type
    if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) {
      setError("Header image must be JPG, PNG, or WebP format");
      return;
    }
    
    // Validate file size (max 2MB)
    if (file.size > 2 * 1024 * 1024) {
      setError("Header image must be less than 2MB");
      return;
    }
    
    // Clear any previous errors
    setError(null);
    
    // Create a preview URL
    const reader = new FileReader();
    reader.onload = (event) => {
      setHeaderImage(event.target?.result as string);
    };
    reader.readAsDataURL(file);
  };

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSuccess(null);
    setIsSubmitting(true);
    
    try {
      // Basic validation
      if (!email || !password) {
        setError('Email and password are required');
        setIsSubmitting(false);
        return;
      }
      
      // Create form data for multipart/form-data submission (for file uploads)
      const formData = new FormData();
      formData.append('email', email);
      formData.append('password', password);
      formData.append('name', name);
      
      // Add store branding fields if provided
      if (storeName) formData.append('storeName', storeName);
      if (storeDescription) formData.append('storeDescription', storeDescription);
      
      // Get the actual File objects from the refs
      const logoFile = logoInputRef.current?.files?.[0];
      const headerFile = headerInputRef.current?.files?.[0];
      
      // Only append files if they exist
      if (logoFile) formData.append('logoFile', logoFile);
      if (headerFile) formData.append('headerFile', headerFile);
      
      // Call the registration API with form data
      const response = await fetch('/api/auth/register', {
        method: 'POST',
        body: formData
        // Don't set Content-Type header, browser will set it with boundary for FormData
      });
      
      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Registration failed');
      }
      
      // Registration successful, show verification message
      setSuccess('Registration successful! Please check your email to verify your account.');
      setRegisteredEmail(email);
      // Clear the form
      setEmail('');
      setPassword('');
      setName('');
    } catch (error) {
      console.error('Registration error:', error);
      setError(error instanceof Error ? error.message : 'Registration failed');
    } finally {
      setIsSubmitting(false);
    }
  };
  
  const handleResendVerification = async () => {
    if (!registeredEmail) return;
    
    try {
      setSuccess(null);
      setError(null);
      
      // Call the resend verification API
      const response = await fetch('/api/auth/resend-verification', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ email: registeredEmail }),
      });
      
      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Failed to resend verification email');
      }
      
      setSuccess('Verification email has been resent');
    } catch (error) {
      console.error('Resend verification error:', error);
      setError(error instanceof Error ? error.message : 'Failed to resend verification email');
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-stone-50 p-4">
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle className="text-stone-800">Create an Account</CardTitle>
          <CardDescription className="text-stone-600 font-light">
            Register to start selling your digital products on alaCart
          </CardDescription>
        </CardHeader>
        <CardContent>
          {error && (
            <Alert variant="destructive" className="mb-4 rounded-xl">
              <AlertCircle className="h-4 w-4" />
              <AlertTitle>Error</AlertTitle>
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}
          
          {success && (
            <Alert className="mb-4 bg-emerald-50 text-emerald-800 border-emerald-200 rounded-xl">
              <CheckCircle2 className="h-4 w-4 text-emerald-600" />
              <AlertTitle>Success</AlertTitle>
              <AlertDescription className="space-y-2">
                <p>{success}</p>
                {registeredEmail && (
                  <Button 
                    variant="outline" 
                    size="sm" 
                    className="mt-2 rounded-2xl border-stone-300 text-emerald-600 hover:bg-emerald-50 hover:text-emerald-700 font-light" 
                    onClick={handleResendVerification}
                    disabled={isSubmitting}
                  >
                    <Mail className="mr-2 h-4 w-4" />
                    {isSubmitting ? 'Sending...' : 'Resend verification email'}
                  </Button>
                )}
              </AlertDescription>
            </Alert>
          )}
          <form onSubmit={handleRegister} className="space-y-6">
            {/* Account Information */}
            <div>
              <h3 className="text-lg font-normal mb-4">Account Information</h3>
              <div className="space-y-4">
                <div>
                  <Label htmlFor="email" className="text-stone-700 font-light">Email</Label>
                  <Input
                    id="email"
                    type="email"
                    value={email}
                    onChange={handleEmailChange}
                    placeholder="you@example.com"
                    required
                    className="border-stone-300 rounded-2xl h-12 font-light focus:border-emerald-500 focus:ring-emerald-500"
                  />
                </div>
                <div>
                  <Label htmlFor="name" className="text-stone-700 font-light">Name (Optional)</Label>
                  <Input
                    id="name"
                    type="text"
                    value={name}
                    onChange={(e) => {
                      setName(e.target.value);
                      setIsNameAutoGenerated(false);
                    }}
                    onFocus={handleNameFocus}
                    onBlur={handleNameBlur}
                    placeholder={isNameAutoGenerated ? name : 'Your name'}
                    className="border-stone-300 rounded-2xl h-12 font-light focus:border-emerald-500 focus:ring-emerald-500"
                  />
                </div>
                <div>
                  <Label htmlFor="password" className="text-stone-700 font-light">Password</Label>
                  <Input
                    id="password"
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="Create a strong password"
                    required
                    className="border-stone-300 rounded-2xl h-12 font-light focus:border-emerald-500 focus:ring-emerald-500"
                  />
                  <p className="text-xs text-stone-500 font-light mt-1">
                    Password must be at least 8 characters with uppercase, lowercase, numbers, and special characters
                  </p>
                </div>
              </div>
            </div>
            
            {/* Store Branding */}
            <div>
              <h3 className="text-lg font-normal mb-2">Store Branding</h3>
              <p className="text-stone-600 font-light mb-4">Customize your store's appearance (optional)</p>
              
              <div className="space-y-4">
                <div>
                  <Label htmlFor="store-name" className="text-stone-700 font-light">Store Name</Label>
                  <Input
                    id="store-name"
                    type="text"
                    value={storeName}
                    onChange={(e) => setStoreName(e.target.value)}
                    placeholder="Digital Craft Co."
                    className="border-stone-300 rounded-2xl h-12 font-light focus:border-emerald-500 focus:ring-emerald-500"
                  />
                </div>
                
                <div>
                  <Label htmlFor="store-description" className="text-stone-700 font-light">Store Description</Label>
                  <textarea
                    id="store-description"
                    value={storeDescription}
                    onChange={(e) => setStoreDescription(e.target.value)}
                    placeholder="Describe your store..."
                    rows={3}
                    className="w-full p-3 border border-stone-300 rounded-2xl font-light focus:ring-emerald-500 focus:border-emerald-500"
                  />
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <Label className="text-stone-700 font-light mb-2 block">Store Logo</Label>
                    <div className="border border-dashed border-stone-300 rounded-2xl p-4 flex flex-col items-center justify-center">
                      {storeLogo ? (
                        <div className="relative w-28 h-28 mb-2">
                          <Image 
                            src={storeLogo} 
                            alt="Store logo" 
                            fill 
                            className="object-contain" 
                            unoptimized={storeLogo.startsWith('data:')} 
                          />
                        </div>
                      ) : (
                        <div className="w-28 h-28 bg-stone-100 rounded-xl flex items-center justify-center mb-2">
                          <Store className="h-10 w-10 text-stone-400" />
                        </div>
                      )}
                      <input
                        type="file"
                        ref={logoInputRef}
                        onChange={handleLogoChange}
                        accept="image/jpeg,image/png,image/webp"
                        className="hidden"
                      />
                      <button
                        type="button"
                        onClick={() => logoInputRef.current?.click()}
                        className="mt-2 px-4 py-2 bg-white border border-stone-300 rounded-xl text-sm font-light text-stone-700 hover:bg-stone-50"
                      >
                        Upload Logo
                      </button>
                      <p className="text-xs text-stone-500 mt-1">JPG, PNG, WebP (max 2MB)</p>
                    </div>
                  </div>
                  
                  <div>
                    <Label className="text-stone-700 font-light mb-2 block">Header Image</Label>
                    <div className="border border-dashed border-stone-300 rounded-2xl p-4 flex flex-col items-center justify-center">
                      {headerImage ? (
                        <div className="relative w-full h-28 mb-2">
                          <Image 
                            src={headerImage} 
                            alt="Header image" 
                            fill 
                            className="object-cover rounded-xl" 
                            unoptimized={headerImage.startsWith('data:')} 
                          />
                        </div>
                      ) : (
                        <div className="w-full h-28 bg-stone-100 rounded-xl flex items-center justify-center mb-2">
                          <Upload className="h-10 w-10 text-stone-400" />
                        </div>
                      )}
                      <input
                        type="file"
                        ref={headerInputRef}
                        onChange={handleHeaderChange}
                        accept="image/jpeg,image/png,image/webp"
                        className="hidden"
                      />
                      <button
                        type="button"
                        onClick={() => headerInputRef.current?.click()}
                        className="mt-2 px-4 py-2 bg-white border border-stone-300 rounded-xl text-sm font-light text-stone-700 hover:bg-stone-50"
                      >
                        Upload Header
                      </button>
                      <p className="text-xs text-stone-500 mt-1">JPG, PNG, WebP (max 2MB)</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <Button 
              type="submit" 
              className="w-full bg-emerald-600 hover:bg-emerald-700 text-white rounded-2xl h-12 font-light" 
              disabled={isSubmitting}>
              {isSubmitting ? 'Creating Store...' : 'Create Store'}
            </Button>
          </form>
          <div className="mt-4 text-center text-sm text-stone-600 font-light">
            Already have an account?{' '}
            <Link href="/login" className="text-emerald-600 hover:text-emerald-700 font-light">
              Log in
            </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
