"use client";

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { AlertCircle, CheckCircle2, Mail } from 'lucide-react';
import Link from 'next/link';

export default function RegisterPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [name, setName] = useState('');
  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(false);
  
  // Generate name from email when email changes
  const handleEmailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newEmail = e.target.value;
    setEmail(newEmail);
    
    // Only auto-fill name if it's empty or was auto-generated
    if (!name || isNameAutoGenerated) {
      const username = newEmail.split('@')[0] || '';
      const formattedName = username
        .split(/[._-]/)
        .map(part => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
      setName(formattedName);
      setIsNameAutoGenerated(true);
    }
  };
  
  // Clear auto-generated name when user focuses on name field
  const handleNameFocus = () => {
    if (isNameAutoGenerated) {
      setName('');
      setIsNameAutoGenerated(false);
    }
  };

  // Restore auto-generated name when name field loses focus and is empty
  const handleNameBlur = () => {
    if (!name.trim() && email) {
      const username = email.split('@')[0] || '';
      const formattedName = username
        .split(/[._-]/)
        .map(part => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
      setName(formattedName);
      setIsNameAutoGenerated(true);
    }
  };
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [registeredEmail, setRegisteredEmail] = useState('');
  const router = useRouter();

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSuccess(null);
    setIsSubmitting(true);

    try {
      // If name is empty, use the username part of the email
      const displayName = name.trim() || email.split('@')[0];
      
      const response = await fetch('/api/auth/register', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ email, password, name: displayName }),
      });

      const data = await response.json();

      if (!response.ok) {
        // Handle validation errors or registration failures
        setError(data.error || 'Registration failed');
        return;
      }

      // Registration successful, show verification message
      setSuccess('Registration successful! Please check your email to verify your account.');
      setRegisteredEmail(email);
      // Clear the form
      setEmail('');
      setPassword('');
      setName('');
    } catch (err) {
      setError('Network error. Please try again.');
      console.error('Registration error:', err);
    } finally {
      setIsSubmitting(false);
    }
  };
  
  const handleResendVerification = async () => {
    if (!registeredEmail) return;
    
    setIsSubmitting(true);
    try {
      const response = await fetch('/api/auth/verify-email', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ email: registeredEmail }),
      });

      if (response.ok) {
        setSuccess('Verification email sent again! Please check your inbox.');
      } else {
        const data = await response.json();
        setError(data.error || 'Failed to send verification email');
      }
    } catch (err) {
      setError('Network error. Please try again.');
      console.error('Verification error:', err);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-stone-50 p-4">
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle className="text-stone-800">Create an Account</CardTitle>
          <CardDescription className="text-stone-600 font-light">
            Register to start selling your digital products on alaCart
          </CardDescription>
        </CardHeader>
        <CardContent>
          {error && (
            <Alert variant="destructive" className="mb-4 rounded-xl">
              <AlertCircle className="h-4 w-4" />
              <AlertTitle>Error</AlertTitle>
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}
          
          {success && (
            <Alert className="mb-4 bg-emerald-50 text-emerald-800 border-emerald-200 rounded-xl">
              <CheckCircle2 className="h-4 w-4 text-emerald-600" />
              <AlertTitle>Success</AlertTitle>
              <AlertDescription className="space-y-2">
                <p>{success}</p>
                {registeredEmail && (
                  <Button 
                    variant="outline" 
                    size="sm" 
                    className="mt-2 rounded-2xl border-stone-300 text-emerald-600 hover:bg-emerald-50 hover:text-emerald-700 font-light" 
                    onClick={handleResendVerification}
                    disabled={isSubmitting}
                  >
                    <Mail className="mr-2 h-4 w-4" />
                    {isSubmitting ? 'Sending...' : 'Resend verification email'}
                  </Button>
                )}
              </AlertDescription>
            </Alert>
          )}
          <form onSubmit={handleRegister} className="space-y-4">
            <div>
              <Label htmlFor="email" className="text-stone-700 font-light">Email</Label>
              <Input
                id="email"
                type="email"
                value={email}
                onChange={handleEmailChange}
                placeholder="you@example.com"
                required
                className="border-stone-300 rounded-2xl h-12 font-light focus:border-emerald-500 focus:ring-emerald-500"
              />
            </div>
            <div>
              <Label htmlFor="name" className="text-stone-700 font-light">Name (Optional)</Label>
              <Input
                id="name"
                type="text"
                value={name}
                onChange={(e) => {
                  setName(e.target.value);
                  setIsNameAutoGenerated(false);
                }}
                onFocus={handleNameFocus}
                onBlur={handleNameBlur}
                placeholder={isNameAutoGenerated ? name : 'Your name'}
                className="border-stone-300 rounded-2xl h-12 font-light focus:border-emerald-500 focus:ring-emerald-500"
              />
            </div>
            <div>
              <Label htmlFor="password" className="text-stone-700 font-light">Password</Label>
              <Input
                id="password"
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="Create a strong password"
                required
                className="border-stone-300 rounded-2xl h-12 font-light focus:border-emerald-500 focus:ring-emerald-500"
              />
              <p className="text-xs text-stone-500 font-light mt-1">
                Password must be at least 8 characters with uppercase, lowercase, numbers, and special characters
              </p>
            </div>
            <Button 
              type="submit" 
              className="w-full bg-emerald-600 hover:bg-emerald-700 text-white rounded-2xl h-12 font-light" 
              disabled={isSubmitting}>
              {isSubmitting ? 'Creating Account...' : 'Create Account'}
            </Button>
          </form>
          <div className="mt-4 text-center text-sm text-stone-600 font-light">
            Already have an account?{' '}
            <Link href="/login" className="text-emerald-600 hover:text-emerald-700 font-light">
              Log in
            </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
